# Generated by Django 4.1.5 on 2023-05-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='BMIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='HCFB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='HCFG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='HFAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='HFAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='MUACB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='MUACG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='WFAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='WFAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='WFHB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='WFHG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD3neg', models.JSONField(blank=True, default={})),
                ('SD2neg', models.JSONField(blank=True, default={})),
                ('SD1neg', models.JSONField(blank=True, default={})),
                ('SD0', models.JSONField(blank=True, default={})),
                ('SD1', models.JSONField(blank=True, default={})),
                ('SD2', models.JSONField(blank=True, default={})),
                ('SD3', models.JSONField(blank=True, default={})),
            ],
        ),
    ]
