# Generated by Django 4.1.5 on 2023-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmib',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmib',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmib',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmib',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmib',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmib',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmib',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmig',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmig',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmig',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmig',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmig',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmig',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bmig',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfb',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfb',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfb',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfb',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfb',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfb',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfb',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfg',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfg',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfg',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfg',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfg',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfg',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hcfg',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfab',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfab',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfab',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfab',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfab',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfab',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfab',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfag',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfag',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfag',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfag',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfag',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfag',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hfag',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacb',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacb',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacb',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacb',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacb',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacb',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacb',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacg',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacg',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacg',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacg',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacg',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacg',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='muacg',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfab',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfab',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfab',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfab',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfab',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfab',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfab',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfag',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfag',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfag',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfag',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfag',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfag',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfag',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhb',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhb',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhb',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhb',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhb',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhb',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhb',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhg',
            name='SD0',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhg',
            name='SD1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhg',
            name='SD1neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhg',
            name='SD2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhg',
            name='SD2neg',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhg',
            name='SD3',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wfhg',
            name='SD3neg',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
