# Generated by Django 4.1.5 on 2023-03-18 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('f_name', models.CharField(max_length=50)),
                ('f_contact', models.CharField(max_length=15)),
                ('m_name', models.CharField(max_length=50)),
                ('m_contact', models.CharField(max_length=15)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('muac', models.IntegerField()),
                ('chestc', models.IntegerField()),
                ('headc', models.IntegerField()),
                ('wtohr', models.IntegerField()),
                ('msclwstng', models.BooleanField()),
                ('stntng', models.BooleanField()),
                ('fngr_dete', models.BooleanField()),
                ('diagnosis', models.CharField(default='Normal', max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Normal'), (2, 'Reported'), (3, 'Checked')], default=1)),
                ('addder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('referred_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reffered_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
