# Generated by Django 4.1.5 on 2023-03-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_alter_child_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='addder',
            new_name='adder',
        ),
    ]
