# Generated by Django 4.1.5 on 2023-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_rename_addder_child_adder'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='city',
            field=models.CharField(default='Bangalore', max_length=50),
            preserve_default=False,
        ),
    ]
